dockerbuild:
	docker build -t felicianoej/arkcontroller:latest -t felicianoej/arkcontroller:v1.0 .

dockerarkrun:
	docker run -it -p 7777:7777 arkcontroller

dockerarkrm:
	docker image rm arkcontroller